import type { StimulusType } from '@/lib/planning/session-blueprints';

export type ExerciseRiskLevel = 'bajo' | 'medio' | 'alto';
export type ExerciseCategory =
  | 'movilidad'
  | 'dedos'
  | 'hombros'
  | 'core'
  | 'traccion'
  | 'tecnica'
  | 'resistencia'
  | 'piernas'
  | 'recuperacion'
  | 'general';

export type CatalogExercise = {
  id: string;
  name: string;
  aliases: string[];
  category: ExerciseCategory;
  stimulusTypes: StimulusType[];
  requiredEquipment: string[];
  riskLevel: ExerciseRiskLevel;
  allowedWithFingerPain: boolean;
  allowedWithShoulderPain: boolean;
  contraindications: string[];
  objective: string;
  defaultDose: string;
  defaultRest: string;
  progressions: string[];
  regressions: string[];
  howTo: string[];
  stopIf: string[];
  commonMistakes: string[];
  feelCues: string[];
  sourceConcept: string;
};

export const EXERCISE_CATALOG: CatalogExercise[] = [
  {
    id: 'movilidad-general',
    name: 'Movilidad general',
    aliases: ['movilidad articular', 'movilidad de hombros y cadera'],
    category: 'movilidad',
    stimulusTypes: ['tecnica_pies', 'fuerza_general', 'movilidad_recuperacion', 'descarga'],
    requiredEquipment: [],
    riskLevel: 'bajo',
    allowedWithFingerPain: true,
    allowedWithShoulderPain: true,
    contraindications: [],
    objective: 'Subir temperatura y preparar articulaciones sin fatiga.',
    defaultDose: '6-8 repeticiones por articulación',
    defaultRest: 'sin descanso largo',
    progressions: ['Aumenta rango solo si no hay dolor.'],
    regressions: ['Reduce rango y velocidad.'],
    howTo: ['Mueve cuello, hombros, muñecas, cadera y tobillos.', 'Usa rango cómodo.', 'Respira lento.'],
    stopIf: ['Dolor punzante.', 'Mareo.', 'Hormigueo.'],
    commonMistakes: ['Rebotar.', 'Forzar rango.', 'Mover rápido sin control.'],
    feelCues: ['Calor ligero.', 'Movimiento fluido.', 'Respiración estable.'],
    sourceConcept: 'Preparación general antes de carga específica.'
  },
  {
    id: 'calentamiento-dinamico',
    name: 'Calentamiento dinámico',
    aliases: ['calentamiento activo', 'entrada en calor dinámica'],
    category: 'general',
    stimulusTypes: ['tecnica_pies', 'fuerza_general', 'resistencia_4x4', 'bloque_trabajado', 'via_trabajada'],
    requiredEquipment: [],
    riskLevel: 'bajo',
    allowedWithFingerPain: true,
    allowedWithShoulderPain: true,
    contraindications: [],
    objective: 'Elevar temperatura con movimientos globales antes del bloque específico.',
    defaultDose: '8-12 minutos',
    defaultRest: 'según respiración',
    progressions: ['Añade coordinación suave.'],
    regressions: ['Camina y haz movilidad simple.'],
    howTo: ['Alterna marcha, skipping suave y movilidad.', 'Mantén conversación posible.', 'No llegues fatigado.'],
    stopIf: ['Mareo.', 'Dolor articular.', 'Fatiga rara.'],
    commonMistakes: ['Empezar demasiado fuerte.', 'Saltar muñecas y hombros.', 'No respirar.'],
    feelCues: ['Calor progresivo.', 'Cuerpo despierto.', 'Ligereza.'],
    sourceConcept: 'Calentamiento progresivo de baja a media intensidad.'
  },
  {
    id: 'barras-escapulares',
    name: 'Barras escapulares',
    aliases: ['scapular pull ups', 'dominadas escapulares'],
    category: 'hombros',
    stimulusTypes: ['fuerza_general', 'antagonistas_preventivo'],
    requiredEquipment: ['pullup_bar'],
    riskLevel: 'medio',
    allowedWithFingerPain: true,
    allowedWithShoulderPain: false,
    contraindications: ['dolor de hombro activo', 'inestabilidad de hombro'],
    objective: 'Activar escápulas y preparar tracción sin flexionar codos.',
    defaultDose: '3 x 6-8 repeticiones',
    defaultRest: '60-90 segundos',
    progressions: ['Pausa 2 segundos abajo y arriba.'],
    regressions: ['Haz activación escapular de pie o con banda.'],
    howTo: ['Cuelga con pies apoyados si hace falta.', 'Baja hombros lejos de orejas.', 'Sube y baja solo escápulas.'],
    stopIf: ['Dolor de hombro.', 'Hormigueo.', 'No puedes controlar la bajada.'],
    commonMistakes: ['Doblar codos.', 'Colgar pasivo.', 'Encoger cuello.'],
    feelCues: ['Espalda alta activa.', 'Hombros estables.', 'Cuello largo.'],
    sourceConcept: 'Estabilidad escapular para tracción segura.'
  },
  {
    id: 'activacion-escapular',
    name: 'Activación escapular',
    aliases: ['escápulas activas', 'prehab hombro'],
    category: 'hombros',
    stimulusTypes: ['tecnica_pies', 'fuerza_general', 'antagonistas_preventivo', 'descarga'],
    requiredEquipment: [],
    riskLevel: 'bajo',
    allowedWithFingerPain: true,
    allowedWithShoulderPain: true,
    contraindications: ['dolor punzante de hombro'],
    objective: 'Preparar hombros y control escapular con baja carga.',
    defaultDose: '2-3 x 8-12 repeticiones',
    defaultRest: '45-60 segundos',
    progressions: ['Añade banda ligera.'],
    regressions: ['Haz el movimiento acostado o contra pared.'],
    howTo: ['Costillas abajo.', 'Lleva escápulas atrás y abajo.', 'Mantén cuello relajado.'],
    stopIf: ['Dolor punzante.', 'Inestabilidad.', 'Hormigueo.'],
    commonMistakes: ['Arquear espalda.', 'Subir hombros a orejas.', 'Mover rápido.'],
    feelCues: ['Hombros firmes.', 'Espalda alta activa.', 'Respiración controlada.'],
    sourceConcept: 'Control de cintura escapular antes de tracción o escalada.'
  },
  {
    id: 'tecnica-pies',
    name: 'Técnica de pies',
    aliases: ['pies silenciosos', 'precisión de pies'],
    category: 'tecnica',
    stimulusTypes: ['tecnica_pies', 'via_trabajada', 'descarga'],
    requiredEquipment: [],
    riskLevel: 'bajo',
    allowedWithFingerPain: true,
    allowedWithShoulderPain: true,
    contraindications: [],
    objective: 'Mejorar precisión, transferencia de peso y economía de movimiento.',
    defaultDose: '4 x 3-5 minutos',
    defaultRest: '2-3 minutos',
    progressions: ['Aumenta complejidad de apoyos o inclinación si hay muro/roca.'],
    regressions: ['Hazlo en el piso sobre una línea.'],
    howTo: ['Mira el apoyo antes de mover.', 'Pisa silencioso.', 'Mueve cadera antes de tirar.'],
    stopIf: ['Dolor aumenta.', 'Pérdida de coordinación.', 'Fatiga cambia la técnica.'],
    commonMistakes: ['Pisar fuerte.', 'No mirar pies.', 'Subir dificultad antes de dominar.'],
    feelCues: ['Pies precisos.', 'Menos tensión en brazos.', 'Cadera estable.'],
    sourceConcept: 'Economía técnica: pies y cadera reducen carga de antebrazo.'
  },
  {
    id: 'pies-pesados',
    name: 'Pies pesados',
    aliases: ['peso en pies', 'descargar antebrazos'],
    category: 'tecnica',
    stimulusTypes: ['tecnica_pies', 'via_trabajada'],
    requiredEquipment: [],
    riskLevel: 'bajo',
    allowedWithFingerPain: true,
    allowedWithShoulderPain: true,
    contraindications: [],
    objective: 'Aprender a cargar peso en los pies para ahorrar agarre.',
    defaultDose: '3 x 4 minutos',
    defaultRest: '2 minutos',
    progressions: ['Añade pausas en posiciones de equilibrio.'],
    regressions: ['Practica de pie contra pared o en suelo.'],
    howTo: ['Empuja el pie antes de mover mano.', 'Mantén brazos largos.', 'Siente el peso en el apoyo.'],
    stopIf: ['Dolor de pie/rodilla.', 'Miedo altera técnica.', 'Fatiga alta.'],
    commonMistakes: ['Tirar con brazos.', 'Mover pies sin mirar.', 'Apurarse.'],
    feelCues: ['Antebrazos más relajados.', 'Apoyos sólidos.', 'Movimiento lento y preciso.'],
    sourceConcept: 'Técnica de pies para eficiencia en roca y muro.'
  },
  {
    id: 'bloque-4x4',
    name: 'Bloque 4x4',
    aliases: ['4x4', 'resistencia en boulder'],
    category: 'resistencia',
    stimulusTypes: ['resistencia_4x4'],
    requiredEquipment: ['gym'],
    riskLevel: 'medio',
    allowedWithFingerPain: false,
    allowedWithShoulderPain: false,
    contraindications: ['sin gym/muro', 'dolor de dedos', 'dolor de hombro', 'principiante'],
    objective: 'Mejorar resistencia específica con bloques submáximos repetidos.',
    defaultDose: '3-4 rondas de 4 bloques submáximos',
    defaultRest: '2-3 minutos entre rondas',
    progressions: ['Aumenta una ronda o reduce descanso ligeramente.'],
    regressions: ['Usa travesía fácil o continuidad en roca muy cómoda.'],
    howTo: ['Elige bloques 2-3 grados bajo máximo.', 'Mantén técnica.', 'Descansa antes del fallo.'],
    stopIf: ['Dolor de dedos.', 'Técnica se rompe.', 'Bombeo máximo.'],
    commonMistakes: ['Elegir bloques muy duros.', 'Descansar poco.', 'Ir al fallo.'],
    feelCues: ['Bombeo controlado.', 'Respiración trabajada.', 'Técnica aún limpia.'],
    sourceConcept: 'Intervalos submáximos de resistencia específica.'
  },
  {
    id: 'bloque-trabajado',
    name: 'Bloque trabajado',
    aliases: ['crux', 'boulder de proyecto'],
    category: 'tecnica',
    stimulusTypes: ['bloque_trabajado'],
    requiredEquipment: ['gym'],
    riskLevel: 'medio',
    allowedWithFingerPain: false,
    allowedWithShoulderPain: false,
    contraindications: ['sin gym', 'dolor de dedos', 'fatiga alta'],
    objective: 'Resolver movimientos difíciles con descanso completo y bajo volumen.',
    defaultDose: '4-6 intentos de 2-4 movimientos',
    defaultRest: '3-5 minutos',
    progressions: ['Aumenta complejidad técnica, no volumen.'],
    regressions: ['Aísla un movimiento más fácil o usa mejores presas.'],
    howTo: ['Define una beta.', 'Haz pocos intentos.', 'Descansa completo.'],
    stopIf: ['Dolor de dedos.', 'Caídas descontroladas.', 'Frustración cambia técnica.'],
    commonMistakes: ['Repetir cansado.', 'No descansar.', 'Cambiar todo cada intento.'],
    feelCues: ['Intentos de calidad.', 'Foco claro.', 'Fatiga controlada.'],
    sourceConcept: 'Práctica deliberada de movimientos límite con volumen controlado.'
  },
  {
    id: 'via-trabajada',
    name: 'Vía trabajada',
    aliases: ['ruta trabajada', 'proyecto en roca'],
    category: 'tecnica',
    stimulusTypes: ['via_trabajada'],
    requiredEquipment: ['rock'],
    riskLevel: 'medio',
    allowedWithFingerPain: true,
    allowedWithShoulderPain: true,
    contraindications: ['sin roca', 'condición insegura', 'dolor que sube'],
    objective: 'Trabajar beta, descansos y secciones clave de un proyecto o ruta real.',
    defaultDose: '3-5 pegues o secciones con descanso completo',
    defaultRest: '4-8 minutos',
    progressions: ['Une secciones o reduce descansos solo si la técnica se mantiene.'],
    regressions: ['Trabaja una sección más fácil o solo lectura/visualización.'],
    howTo: ['Lee desde el suelo.', 'Elige una intención.', 'Anota beta y sensaciones.'],
    stopIf: ['Dolor sube a 3/10.', 'Fatiga altera caídas.', 'Miedo impide decidir.'],
    commonMistakes: ['Dar pegues sin plan.', 'No descansar.', 'Ignorar pies.'],
    feelCues: ['Aprendizaje claro.', 'Mejor beta.', 'Esfuerzo manejable.'],
    sourceConcept: 'Planificación táctica de proyecto en roca.'
  },
  {
    id: 'suspensiones-asistidas',
    name: 'Suspensiones asistidas',
    aliases: ['colgadas asistidas', 'suspensión con pies apoyados'],
    category: 'dedos',
    stimulusTypes: ['fuerza_dedos_submaxima', 'fuerza_general'],
    requiredEquipment: ['pullup_bar'],
    riskLevel: 'medio',
    allowedWithFingerPain: false,
    allowedWithShoulderPain: false,
    contraindications: ['dolor de dedos activo', 'hombro inestable', 'sin barra'],
    objective: 'Construir tolerancia de agarre y hombro con carga descargada.',
    defaultDose: '3 x 8-10 segundos',
    defaultRest: '90 segundos',
    progressions: ['Quita asistencia gradualmente.'],
    regressions: ['Haz activación escapular de pie y extensores.'],
    howTo: ['Apoya pies.', 'Hombros activos.', 'Suelta antes del fallo.'],
    stopIf: ['Dolor de dedos.', 'Hombro se siente inestable.', 'Pérdida de agarre.'],
    commonMistakes: ['Colgar pasivo.', 'Ir al fallo.', 'Apretar arqueado.'],
    feelCues: ['Carga moderada.', 'Escápulas firmes.', 'Dedos sin dolor.'],
    sourceConcept: 'Carga isométrica submáxima con asistencia.'
  },
  {
    id: 'extensores-banda',
    name: 'Extensores de dedos con banda',
    aliases: ['aperturas de dedos con banda', 'banda extensores'],
    category: 'dedos',
    stimulusTypes: ['antagonistas_preventivo', 'movilidad_recuperacion', 'descarga'],
    requiredEquipment: ['bands'],
    riskLevel: 'bajo',
    allowedWithFingerPain: true,
    allowedWithShoulderPain: true,
    contraindications: ['dolor punzante al abrir dedos'],
    objective: 'Activar extensores y equilibrar carga de flexores de dedos.',
    defaultDose: '2-3 x 12-15 repeticiones',
    defaultRest: '30-45 segundos',
    progressions: ['Usa banda apenas más firme.'],
    regressions: ['Haz aperturas sin banda.'],
    howTo: ['Muñeca neutra.', 'Abre dedos lento.', 'Regresa controlado.'],
    stopIf: ['Dolor sube a 3/10.', 'Dolor punzante.', 'Hormigueo.'],
    commonMistakes: ['Banda muy dura.', 'Doblar muñeca.', 'Ir rápido.'],
    feelCues: ['Dorso de mano activo.', 'Antebrazo ligero.', 'Cero dolor articular.'],
    sourceConcept: 'Trabajo antagonista de dedos para prevención.'
  },
  {
    id: 'aperturas-dedos-banda',
    name: 'Aperturas de dedos con banda',
    aliases: ['apertura con banda', 'dedos con banda'],
    category: 'dedos',
    stimulusTypes: ['antagonistas_preventivo', 'movilidad_recuperacion'],
    requiredEquipment: ['bands'],
    riskLevel: 'bajo',
    allowedWithFingerPain: true,
    allowedWithShoulderPain: true,
    contraindications: ['dolor punzante al extender dedos'],
    objective: 'Recuperar control de apertura y tolerancia suave de extensores.',
    defaultDose: '2 x 15 repeticiones',
    defaultRest: '30 segundos',
    progressions: ['Pausa 1 segundo abierto.'],
    regressions: ['Sin banda, solo apertura activa.'],
    howTo: ['Coloca banda ligera.', 'Abre sin bloquear muñeca.', 'Vuelve lento.'],
    stopIf: ['Dolor aumenta.', 'Hormigueo.', 'Fatiga cambia control.'],
    commonMistakes: ['Cerrar de golpe.', 'Usar banda pesada.', 'Subir hombros.'],
    feelCues: ['Dorso de mano trabaja.', 'Antebrazo se calienta.', 'Movimiento suave.'],
    sourceConcept: 'Extensores de dedos y equilibrio de antebrazo.'
  },
  {
    id: 'finger-curls',
    name: 'Finger curls',
    aliases: ['curl de dedos', 'flexión de dedos'],
    category: 'dedos',
    stimulusTypes: ['fuerza_dedos_submaxima', 'antagonistas_preventivo'],
    requiredEquipment: ['weights'],
    riskLevel: 'medio',
    allowedWithFingerPain: false,
    allowedWithShoulderPain: true,
    contraindications: ['dolor de dedos', 'sin pesas', 'principiante'],
    objective: 'Fortalecer flexores de dedos con rango controlado y carga baja.',
    defaultDose: '2-3 x 8-10 repeticiones',
    defaultRest: '90 segundos',
    progressions: ['Sube carga mínima si no hay dolor por 2 semanas.'],
    regressions: ['Usa pelota suave o isométrico sin carga.'],
    howTo: ['Carga ligera.', 'Muñeca neutra.', 'Rango lento.'],
    stopIf: ['Dolor de dedos.', 'Molestia en poleas.', 'Pérdida de control.'],
    commonMistakes: ['Carga pesada.', 'Ir al fallo.', 'Mover muñeca.'],
    feelCues: ['Antebrazo activo.', 'Dedos sin pinchazo.', 'Control lento.'],
    sourceConcept: 'Fuerza específica con carga externa controlada.'
  },
  {
    id: 'plancha-frontal',
    name: 'Plancha frontal',
    aliases: ['core plancha', 'plank'],
    category: 'core',
    stimulusTypes: ['core', 'fuerza_general'],
    requiredEquipment: [],
    riskLevel: 'bajo',
    allowedWithFingerPain: true,
    allowedWithShoulderPain: true,
    contraindications: ['dolor lumbar agudo'],
    objective: 'Construir tensión corporal para transferir fuerza en escalada.',
    defaultDose: '3 x 20-40 segundos',
    defaultRest: '60 segundos',
    progressions: ['Aumenta 5 segundos o eleva un pie.'],
    regressions: ['Apoya rodillas.'],
    howTo: ['Codos bajo hombros.', 'Costillas abajo.', 'Respira sin perder línea.'],
    stopIf: ['Dolor lumbar.', 'No puedes respirar.', 'Cadera se hunde.'],
    commonMistakes: ['Arquear lumbar.', 'Aguantar aire.', 'Mirar al frente.'],
    feelCues: ['Abdomen activo.', 'Glúteos firmes.', 'Cuello relajado.'],
    sourceConcept: 'Tensión corporal específica para escalada.'
  },
  {
    id: 'hollow-body',
    name: 'Hollow body',
    aliases: ['hollow body hold', 'posición hollow'],
    category: 'core',
    stimulusTypes: ['core', 'fuerza_general'],
    requiredEquipment: [],
    riskLevel: 'bajo',
    allowedWithFingerPain: true,
    allowedWithShoulderPain: true,
    contraindications: ['dolor lumbar agudo'],
    objective: 'Mejorar control de tronco para desplomes, taloneos y tensión.',
    defaultDose: '3 x 15-25 segundos',
    defaultRest: '60 segundos',
    progressions: ['Extiende piernas más lejos.'],
    regressions: ['Dobla rodillas o haz dead bug.'],
    howTo: ['Exhala.', 'Pega costillas abajo.', 'Eleva piernas solo si no se arquea la espalda.'],
    stopIf: ['Dolor lumbar.', 'Calambre fuerte.', 'Pérdida de control.'],
    commonMistakes: ['Arquear espalda.', 'Tensar cuello.', 'Aguantar aire.'],
    feelCues: ['Abdomen profundo.', 'Espalda estable.', 'Respiración corta posible.'],
    sourceConcept: 'Control lumbopélvico para tensión corporal.'
  },
  {
    id: 'pistol-squat-regresion',
    name: 'Pistol squat y regresión',
    aliases: ['sentadilla a una pierna', 'pistol asistida'],
    category: 'piernas',
    stimulusTypes: ['fuerza_general', 'core'],
    requiredEquipment: [],
    riskLevel: 'medio',
    allowedWithFingerPain: true,
    allowedWithShoulderPain: true,
    contraindications: ['dolor de rodilla', 'pinzamiento de cadera'],
    objective: 'Construir fuerza unilateral de pierna y control de cadera.',
    defaultDose: '3 x 4-6 por lado o regresión a silla',
    defaultRest: '90 segundos',
    progressions: ['Baja a menor altura o controla más rango.'],
    regressions: ['Sentadilla a silla o split squat.'],
    howTo: ['Pie firme.', 'Rodilla alineada.', 'Baja lento.'],
    stopIf: ['Dolor de rodilla.', 'Dolor de cadera.', 'Pérdida de equilibrio.'],
    commonMistakes: ['Rodilla cae adentro.', 'Rebotar.', 'Perder postura.'],
    feelCues: ['Glúteo activo.', 'Cadera estable.', 'Pie empuja el piso.'],
    sourceConcept: 'Fuerza de piernas para empuje y posiciones de escalada.'
  },
  {
    id: 'trx-row',
    name: 'Remo en TRX',
    aliases: ['remo con trx', 'remo en anillas'],
    category: 'traccion',
    stimulusTypes: ['fuerza_general', 'antagonistas_preventivo'],
    requiredEquipment: ['trx'],
    riskLevel: 'medio',
    allowedWithFingerPain: true,
    allowedWithShoulderPain: false,
    contraindications: ['sin TRX', 'dolor de hombro activo'],
    objective: 'Desarrollar tracción horizontal y estabilidad escapular.',
    defaultDose: '3 x 8-10 repeticiones',
    defaultRest: '90 segundos',
    progressions: ['Inclina más el cuerpo.'],
    regressions: ['Camina hacia atrás y reduce inclinación.'],
    howTo: ['Cuerpo en línea.', 'Tira con espalda.', 'Baja lento.'],
    stopIf: ['Dolor de hombro.', 'Codo molesta.', 'No controlas la bajada.'],
    commonMistakes: ['Encoger hombros.', 'Arquear lumbar.', 'Tirar con cuello.'],
    feelCues: ['Espalda trabaja.', 'Hombros estables.', 'Core activo.'],
    sourceConcept: 'Tracción horizontal submáxima para acondicionamiento.'
  },
  {
    id: 'campus-controlado',
    name: 'Campus controlado',
    aliases: ['campus board', 'ladder campus'],
    category: 'dedos',
    stimulusTypes: ['fuerza_dedos_submaxima', 'bloque_trabajado'],
    requiredEquipment: ['campus'],
    riskLevel: 'alto',
    allowedWithFingerPain: false,
    allowedWithShoulderPain: false,
    contraindications: ['sin campus', 'sin experiencia campus', 'dolor de dedos', 'principiante'],
    objective: 'Desarrollar potencia coordinada solo para perfiles avanzados sin dolor.',
    defaultDose: '3-4 series de baja cantidad',
    defaultRest: '3-5 minutos',
    progressions: ['Aumenta distancia solo tras varias semanas sin dolor.'],
    regressions: ['Bloque trabajado con pies o tracción submáxima.'],
    howTo: ['Calienta muy bien.', 'Usa agarre abierto.', 'Pocos intentos de calidad.'],
    stopIf: ['Dolor de dedos.', 'Dolor de hombro/codo.', 'Pérdida de coordinación.'],
    commonMistakes: ['Demasiado volumen.', 'Arqueo máximo.', 'Usarlo fatigado.'],
    feelCues: ['Potencia limpia.', 'Descanso completo.', 'Cero dolor.'],
    sourceConcept: 'Potencia avanzada; alto riesgo si se usa fuera de contexto.'
  },
  {
    id: 'hangboard-submaximo',
    name: 'Hangboard submáximo',
    aliases: ['tabla multipresa submáxima', 'fingerboard submáximo'],
    category: 'dedos',
    stimulusTypes: ['fuerza_dedos_submaxima'],
    requiredEquipment: ['hangboard'],
    riskLevel: 'alto',
    allowedWithFingerPain: false,
    allowedWithShoulderPain: false,
    contraindications: ['sin hangboard', 'dolor de dedos', 'principiante', 'menor de 16'],
    objective: 'Entrenar fuerza de dedos con margen amplio y agarre seguro.',
    defaultDose: '4 x 7-10 segundos submáximos',
    defaultRest: '2-3 minutos',
    progressions: ['Aumenta carga mínima solo sin dolor.'],
    regressions: ['Suspensión asistida o extensores con banda.'],
    howTo: ['Agarre abierto.', 'Hombros activos.', 'Corta antes de fallo.'],
    stopIf: ['Dolor de dedos.', 'Dolor punzante.', 'Hombro se siente inestable.'],
    commonMistakes: ['Max hangs.', 'Arqueo máximo.', 'Descansar poco.'],
    feelCues: ['Carga controlada.', 'Dedos seguros.', 'Dos repeticiones en reserva.'],
    sourceConcept: 'Fuerza de dedos submáxima con progresión conservadora.'
  }
];

export function getExerciseById(id: string) {
  return EXERCISE_CATALOG.find((exercise) => exercise.id === id) ?? null;
}

export function getExercisesForStimulus(stimulusType: StimulusType) {
  return EXERCISE_CATALOG.filter((exercise) => exercise.stimulusTypes.includes(stimulusType));
}

export function getExerciseCatalogSize() {
  return EXERCISE_CATALOG.length;
}
