export const CHAT_MAX_OUTPUT_TOKENS = 500;
export const PLAN_SKELETON_MAX_OUTPUT_TOKENS = 3000;
export const PLAN_SESSION_MAX_OUTPUT_TOKENS = 2500;
export const PLAN_FINAL_MAX_OUTPUT_TOKENS = 6000;

export const MAX_EXERCISE_CANDIDATES_PER_SESSION = 12;
